### ISSUE TITLE
Count's users own profile view

### ISSUE THREAD

**Issue by ranamahmud** [antonkomarev/github-profile-views-counter#11]
Currently, the GitHub profile view counter increases counter by one when a user reloads his GitHub profile page. For more accurate counter it should exclude profile views by the owner of the GitHub repository.

**Comment by antonkomarev** [comment]
Hi @ranamahmud!

In short: it is impossible.

GitHub passes all images URLs through their [GitHub Camo proxy service](https://github.blog/2010-11-13-sidejack-prevention-phase-3-ssl-proxied-assets/). This means that only GitHub can track personal information, such as visitors User Agent or IP address. Third party cloud service stores only views timestamps and total count of views.

**Comment by ranamahmud** [comment]
We can try adding a JavaScript script in the rmd file that'll check the current username in the browser's address bar and if that matches the repo owner's name then it'll exclude the view count.

**Comment by antonkomarev** [comment]
We can't add JS, it's a markdown in GitHub. GitHub protects users from such things. Otherwise it will be security issue and people will be able to place tracking cookies. And GitHub doing it right.

**Comment by antonkomarev** [comment]
![Screenshot_2020-07-22 antonkomarev antonkomarev](https://user-images.githubusercontent.com/1849174/88124209-4091f000-cbd5-11ea-8c90-6237f6ad0c60.png)

`<script>` tag is encoded.

**Comment by ranamahmud** [comment]
Got it.

**Comment by ksdkamesh99** [comment]
Hi @ranamahmud I too got the same idea but now it is cleared . Thanks for clarifying @antonkomarev .

**Comment by vishalcseiitg** [comment]
Thanks for sharing
