### ISSUE TITLE
Format number?

### ISSUE THREAD

**Issue by JellyBellyDev** [antonkomarev/github-profile-views-counter#12]
What do you think about the format number in the views counter?
![Schermata 2020-07-22 alle 17 34 04](https://user-images.githubusercontent.com/190820/88196499-8c7a7e80-cc41-11ea-97a5-29e9dd529854.png)

`2938` => `2,938`?

**Comment by antonkomarev** [comment]
@JellyBellyDev good idea! And pretty easy to implement :wink:

**Comment by antonkomarev** [comment]
Number format was added.

**Comment by MuhaddiMu** [comment]
Hey @antonkomarev What if we make 1000 to 1K, 10000 to 10K and so on this will be more readable. 

Thinking ahead of time; instead of displaying 7329587, we should display 7.3 Million

This thread might be helpful https://stackoverflow.com/questions/9461621/format-a-number-as-2-5k-if-a-thousand-or-more-otherwise-900

**Comment by antonkomarev** [comment]
@MuhaddiMu I've thought about it, but after counter will reach 1K you will stop seeing it's updates for a long time. And there is no way to insert detailed numbers in popup on hover.

**Comment by MuhaddiMu** [comment]
That makes sense!

**Comment by antonkomarev** [comment]
@MuhaddiMu but every day after seeing spam hammering my server I'm thinking about hiding detailed numbers. Maybe it will decrease amount of abuse.

**Comment by MuhaddiMu** [comment]
Yes, this is a good point or maybe you can set some sort of throttling. A specific number of request in a minute for a specific user

**Comment by antonkomarev** [comment]
There is no way to determine who is doing request. All requests comes from GitHub proxy server.

**Comment by antonkomarev** [comment]
If there will be the way to determine who is doing request, I'd better create unique visitors count instead of views count.
