### ISSUE TITLE
Adding new style for the badge?

### ISSUE THREAD

**Issue by KarthikNayak024** [antonkomarev/github-profile-views-counter#14]
Can you please add **for-the-badge** style for the badges?

**Comment by antonkomarev** [comment]
@KarthikNayak024 you could add it to https://github.com/badges/poser library because this app using it for the badge rendering.

**Comment by KarthikNayak024** [comment]
How to add that? I couldn't find anything in Contribution.md file.

**Comment by ent3r** [comment]
@KarthikNayak024 https://github.com/badges/poser/blob/master/CONTRIBUTING.md

**Comment by antonkomarev** [comment]
Closing this issue since its related to other repository.

**Comment by antonkomarev** [comment]
Feature will be added as soon as this feature request will be implemented: https://github.com/badges/poser/issues/55

**Comment by antonkomarev** [comment]
We can add `for-the-badge` style to the README [Styles section](https://github.com/antonkomarev/github-profile-views-counter#styles) and bump minimum `"badges/poser"` version in the composer.json to "^2.3". I will try to upgrade service on this weekend.

**Comment by antonkomarev** [comment]
@Karthik-Nayak98 new style `for-the-badge` has been released: #45

**Comment by Karthik-Nayak98** [comment]
Thanks @antonkomarev
