### ISSUE TITLE
Adding a way for people to reset their own badge

### ISSUE THREAD

**Issue by theS1LV3R** [antonkomarev/github-profile-views-counter#15]
Would it be possible to add a way for people to reset their badge? Authentication could be done using OAuth2 to make sure people only can reset their own badges.

This would be useful for example if you edit your readme a lot, and go back and fourth between the editor and preview tab. Each time you then go to the preview tab it increases the counter. That's why my counter is approaching 100, even though im likely only at like 5 (10 if im lucky)

**Comment by antonkomarev** [comment]
@ent3r I will think about it. Thank you for the suggestion!

**Comment by fabiosangregorio** [comment]
On this note, could it be possible (through OAuth2 or something else) to exclude yourself from the views count? I'm thinking something like "Do not increase the counter if I'm viewing the readme logged in as myself".

**Comment by ent3r** [comment]
That's not possible. Github images are served through a proxy, and because of that have the same IP. It's impossible to filter out users

**Comment by antonkomarev** [comment]
@ent3r is absolutely right. There is no way to determine visitor username, UA or IP address, so there is no way do not track yourself. We can't even track unique visits count. Because of this, this tool is as simple as possible.

**Comment by antonkomarev** [comment]
@theS1LV3R To implement counter reset we need to add login feature. It's not that easy and will require to rewrite a lot of the code.

But I have better alternative. I've hardly worked and recently launched [Ÿ HŸPE](https://yhype.halp.im) (open alpha), brand new service for GitHub users. You can login using GitHub account, and it will generate link with invisible counter for your profile README file. Statistics will be collected to private dashboard. Right now it includes profile views and followers history (following + unfollowing). In next few months we will have repository traffic statistics without 14 days GitHub limitation.

**Comment by theS1LV3R** [comment]
Looks good!

**Comment by antonkomarev** [comment]
I'm spending all my free time for the improvements, and I think that counters reset will appear in Ÿ HŸPE faster than here.

**Comment by theS1LV3R** [comment]
I just logged in, it looked good!

**Comment by antonkomarev** [comment]
@theS1LV3R @fabiosangregorio @SudhanPlayz @brookmg I found a way how to implement counter reset without reimplementing all the GitHub authorization flow in this repository (what looks like an overkill for this project).

You can login to the Ÿ HŸPE and visit GHPVC reset page: https://yhype.me/ghpvc

![Reset GHPVC on Ÿ HŸPE](https://user-images.githubusercontent.com/1849174/103422269-a5ed0280-4bb1-11eb-9464-2643f0a55d8d.png)

**Comment by brookmg** [comment]
is `yhype` opensource ?

**Comment by antonkomarev** [comment]
@brookmg It uses GHPVC for profile views feature under the hood. All other parts of the service are closed source for now. At this moment there are no plans to make it free open source project. It's free proprietary software. But we'll see in the future.
