### ISSUE TITLE
Add support for for-the-badge style

### ISSUE THREAD

**Issue by deep5050** [antonkomarev/github-profile-views-counter#16]
It would be great to add for-the-badge styled output :)

**Comment by antonkomarev** [comment]
This question was raised before #14

**Comment by antonkomarev** [comment]
Feature will be added as soon as this feature request will be implemented: https://github.com/badges/poser/issues/55

**Comment by antonkomarev** [comment]
@deep5050 new style `for-the-badge` has been released: #45
