### ISSUE TITLE
Typo!

### ISSUE THREAD

**Issue by LifeOfJona** [antonkomarev/github-profile-views-counter#18]
"lightgrey" is not valid but "lightgray" does work. 

Please rename the colour, thanks :)

**Comment by antonkomarev** [comment]
Good catch @LifeOfJona!
This feature will appear as soon as this issue will be resolved: https://github.com/badges/poser/issues/56

**Comment by antonkomarev** [comment]
Fixed. 2 new colors were added:
- gray
- lightgrey
