### ISSUE TITLE
profile views

### ISSUE THREAD

**Issue by kambleaa007** [antonkomarev/github-profile-views-counter#21]
for every refresh from same machine, i have seen profile views getting incremented,
not a big issue at all,
its maybe work as expected,
just want, you to know!!!
(we can check ip address and then only increment)

Thanks,
Ashish

**Comment by antonkomarev** [comment]
GitHub passes all images URLs through their [GitHub Camo proxy service](https://github.blog/2010-11-13-sidejack-prevention-phase-3-ssl-proxied-assets/).
This means that only GitHub can track personal information, such as visitors User Agent or IP address.
Third party cloud service stores only views timestamps and total count of views.
