### ISSUE TITLE
Adding the for-the-badge design

### ISSUE THREAD

**Issue by Wafelack** [antonkomarev/github-profile-views-counter#23]
It could be cool if we could have the for-the-badge design for this profile views badge

**Comment by antonkomarev** [comment]
Hi @Wafelack! This question has been raised before:
- #14 
- #16 

In short, this repository uses "poser" library for the badges rendering, so this feature should be added to it first. There is a feature request for it: https://github.com/badges/poser/issues/55

**Comment by Wafelack** [comment]
Ok thanks :)

**Comment by Harukisatoh** [comment]
Any updates on this issue?

**Comment by antonkomarev** [comment]
@Harukisatoh It will be added as soon as this issue will be resolved https://github.com/badges/poser/issues/55

**Comment by antonkomarev** [comment]
@Wafelack @Harukisatoh new style `for-the-badge` has been released:
https://github.com/antonkomarev/github-profile-views-counter/pull/45

**Comment by Harukisatoh** [comment]
> @Wafelack @Harukisatoh new style `for-the-badge` has been released: #45

Thats awesome, thanks for letting me know :D
