### ISSUE TITLE
Please make a github repo views counter!!!

### ISSUE THREAD

**Issue by navaneethkm004** [antonkomarev/github-profile-views-counter#24]

**Comment by antonkomarev** [comment]
Hey @navaneethkm004! I have something better than tracking pixel for repositories. Just try my service https://yhype.me for free.

Repository statistics:
![EqRQFp7XMAEe3se](https://user-images.githubusercontent.com/1849174/104131449-77c4ab00-5387-11eb-84e5-ae556a4be6c8.png)

Repository stars:
![EqRQYMkXAAAlGvy](https://user-images.githubusercontent.com/1849174/104131451-798e6e80-5387-11eb-8920-a186505411af.jpeg)

**Comment by navaneethkm004** [comment]
Okay!! Thanks

**Comment by navaneethkm004** [comment]
But the thing is that i want a button like thingy and also it's closed source!!

**Comment by antonkomarev** [comment]
Yes, its closed source. Its very complicated service which is in beta phase rught now. I've spent months to make it work and not ready to thoe it to open source for now. Its free proprietary software at this moment.

**Comment by antonkomarev** [comment]
Button cannot count unique users, but my service can do it.

**Comment by navaneethkm004** [comment]
Can you make a button like thingy integrated with your analytics tool? Let the both be closed source as it is and make it like https://api.yhype.me/?username=NAME&repo=REPO And integrate it to a button?

**Comment by antonkomarev** [comment]
You can make a pull request with this feature.
I will think wnd calculate if my server can handle it. I don't make money for it and nobody donates, so it's not that cheap to store all this data. Right now this small feature storage is more than 500mb already. And repository counters will require disk space too.
