### ISSUE TITLE
Adjust the font size

### ISSUE THREAD

**Issue by spencer741** [antonkomarev/github-profile-views-counter#25]
Thank you for this repo! Simple and professional. I am making my img tag larger to fit better with my readme, but I was wondering if it is possible to implement a font size feature.

Thanks again!

**Comment by antonkomarev** [comment]
Badge generation is delegated to the 3rd party library https://github.com/badges/poser
Add this functionality to it and we will able to use it as well!

Related issues: #23 #16 #14
