### ISSUE TITLE
Badge displays weirdly on Edge

### ISSUE THREAD

**Issue by Andre601** [antonkomarev/github-profile-views-counter#26]
When viewing the Profile Views badge in Edge is there a odd gap between the "e" and "w" of "views". (See image)

I doubt that it's a browser thing,

![image](https://user-images.githubusercontent.com/11576465/109750897-956efd80-7bdd-11eb-88af-1dc8f155034c.png)

**Comment by antonkomarev** [comment]
Hey @Andre601! This project using popular third party library to generate badges: https://github.com/badges/poser/
I think it would be better to raise an issue there.

**Comment by Andre601** [comment]
Considering the badges themself are from shields.io would my guess be more to raise an issue on their main issue tracker, unless this really is a poser-related bug.

Anyway, thanks for this info.
