### ISSUE TITLE
SSL Certificate Invalid/Expired

### ISSUE THREAD

**Issue by brandonsaldan** [antonkomarev/github-profile-views-counter#29]
GitHub no longer displays view counter badges due to a problem with komarev.com's SSL certificate. Chrome throws the `NET::ERR_CERT_DATE_INVALID` error. Pretty sure the certificate expired.

**Comment by elttayman** [comment]
Yes, if you go to the link of the counter you will see that the certificate ended today 16 of April

**Comment by antonkomarev** [comment]
Thanks for the notification, guys! Certificate reissue has died. We are working on it!

**Comment by aheze** [comment]
Yep, just noticed. Thank you so much for providing this service for free too!

**Comment by antonkomarev** [comment]
Certificate restored! Thank you for your patience. We will try to avoid such issues in the future.
