### ISSUE TITLE
XSS in label parameter

### ISSUE THREAD

**Issue by ArthurFiorette** [antonkomarev/github-profile-views-counter#30]
I was creating my readme and i thought why not test if a script tag would work here? hahaha. It worked. 

https://komarev.com/ghpvc/?username=arthurfiorette&style=flat-square&color=add8e6&label=%3Cscript%3Ealert(%27script%20with%20spaces!%27)%3C/script%3E

I haven't tested it much, but sometimes the server returns a 500 error, like when there is invalid html and so on. maybe it won't go anywhere, but it needs a check.

**Comment by antonkomarev** [comment]
Thank you for the report @ArthurFiorette!
This image not meant to be called directly from komarev.com domain. GitHub proxies all images, JS scripts are not working. However, it would be good to fix this problem.
PRs are welcome.

**Comment by antonkomarev** [comment]
Resolved with #31 by @JaderH
