### ISSUE TITLE
YHYPE Website down?

### ISSUE THREAD

**Issue by GrandMoff100** [antonkomarev/github-profile-views-counter#36]
I've tried visiting https://yhype.me on many devices and it doesn't seem to be online whenever I try. My browser keeps saying the server took too long to respond. Do you have any insight or am I missing anything?

**Comment by antonkomarev** [comment]
Working for me. I'm on holidays, will look on it 10th of November

**Comment by antonkomarev** [comment]
> I've tried visiting https://yhype.me on many devices and it doesn't seem to be online whenever I try. My browser keeps saying the server took too long to respond. Do you have any insight or am I missing anything? 

Are you receiving this error while visiting website as guest? If so, its not a application issue, it's network issue

**Comment by GrandMoff100** [comment]
Never mind it working fine now.

**Comment by antonkomarev** [comment]
@GrandMoff100 you could write to the community chat to receive feedback quicker: https://discord.gg/EsZqQFez

**Comment by GrandMoff100** [comment]
Good to know. Thanks.
