### ISSUE TITLE
[Enhancement]Counts a person's own view as well.

### ISSUE THREAD

**Issue by arnabdutta2194** [antonkomarev/github-profile-views-counter#37]
Hi Anton,

You have made a great project but I think with one enhancement it would be perfect. The counter considers the user's own count as well. Would it be possible to clone this project to another repo and make a slight enhancement to it? Or if you can incorporate the enhancement in the same repo it would be very helpful.

I am a novice in programming so apologizing beforehand if this issue is laughable 🍡

**Comment by arnabdutta2194** [comment]
If it is somehow possible to track the user's username and then implement the logic to ignore his own view.

**Comment by antonkomarev** [comment]
@arnabdutta2194 it is impossible. You can read read details here: https://github.com/antonkomarev/github-profile-views-counter#why-does-the-counter-increase-every-time-the-page-is-reloaded
