### ISSUE TITLE
My Github username was changed.

### ISSUE THREAD

**Issue by hiccupsoft** [antonkomarev/github-profile-views-counter#39]
My github username was `hiccup1991` before.
So your API is counting for `hiccup1991`.
But I changed my username to `hiccupsoft`.
So I tried to change the username of your API to `hiccupsoft`. In this case, the visit count of my profile is down to zero.
Is there any approach to keep my current visit count and change the username of your API?

**Comment by antonkomarev** [comment]
@hiccupsoft I could recommend you to start using https://yhype.me. This feature included automatically there.
