### ISSUE TITLE
[Design flaw] Kerning for the 'w' in "Profile views" text is messed up

### ISSUE THREAD

**Issue by TheAlienDrew** [antonkomarev/github-profile-views-counter#41]
Here's an example of my profile views badge as of today (1/23/2022 @ 5:53 AM PST):
- [![image](https://user-images.githubusercontent.com/19640692/150681833-79648b37-c2a8-4c19-8e7d-38b257101b69.png)](#)

Underlined is where the issue occurs:
- [![image](https://user-images.githubusercontent.com/19640692/150681950-19e9ed09-8273-4fdf-a0a0-85485bde9199.png)](#)

As you can see, for some reason, more space has been added to the left of the 'w', causing it to also intersect the 's' in the word "views".

**Comment by antonkomarev** [comment]
This project uses https://github.com/badges/poser library for badge rendering. This issue should be targeted there.

**Comment by TheAlienDrew** [comment]
Noticed there's a similar issue there https://github.com/badges/poser/issues/72, going to close this.
