### ISSUE TITLE
Image Not Showing

### ISSUE THREAD

**Issue by rizkytegar** [antonkomarev/github-profile-views-counter#47]
https://camo.githubusercontent.com/d623505e1cfd15c17382a974e808708e996776ed7cabc5780ca50600cc5df7c1/68747470733a2f2f6b6f6d617265762e636f6d2f67687076632f3f757365726e616d653d72697a6b797465676172266c6162656c3d72697a6b7974656761722b70726f66696c652b76697369746f72

Is it an error?

when I open the url above it will display a message like this.

```
Error Fetching Resource
```

it also doesn't show up on my profile

```
   <img src="https://komarev.com/ghpvc/?username=rizkytegar&label=rizkytegar+profile+visitor">
```

Only showing broken image icon

**Comment by philip-gai** [comment]
I am seeing this also. Looks like it's down?

**Comment by ZhiyuanMa2017** [comment]
Same error.
I can open link like `https://komarev.com/ghpvc/?username=rizkytegar&label=rizkytegar+profile+visitor`
But it doesn't show on README page.

**Comment by impratik7** [comment]
Facing similar issue. Seems it is down.

**Comment by antonkomarev** [comment]
We've moved our server to another IP address, it seems that it is not available from some locations. Researching this issue.

**Comment by antonkomarev** [comment]
Could anybody confirm that issue still actual?

**Comment by rizkytegar** [comment]
this problem is not solved

**Comment by antonkomarev** [comment]
Monitoring does reports OK: https://updown.io/iipa

**Comment by ZhiyuanMa2017** [comment]
Sat Mar 19 02:49:01 EDT 2022

This is the code in my README:
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/29819347/159110766-48c60b2c-e9b0-46f5-be14-3c7d99511c07.png">

This is how the link shows in browser:
<img width="895" alt="image" src="https://user-images.githubusercontent.com/29819347/159110757-5da6fbe0-be78-45d3-a857-d94ae9696424.png">

This is how the links shows in README.md:
<img width="189" alt="image" src="https://user-images.githubusercontent.com/29819347/159110804-99aafa38-521e-42df-bb35-653a8d7ad520.png">

My README repo: https://github.com/ZhiyuanMa2017/ZhiyuanMa2017/

**Comment by antonkomarev** [comment]
That's really strange. I'll try to reach GitHub support, maybe GitHub Camo service cached bad responses and won't re-fetch them :\

**Comment by septiyp** [comment]
has it worked? I see it's still an error

**Comment by probabilityhill** [comment]
I was facing the same problem, but now it seems to be solved.  (If it doesn't show up , try reloading)

<img alt="my GitHub profile views" src="https://komarev.com/ghpvc/?username=probabilityhill&color=yellow" />

**Comment by philip-gai** [comment]
@antonkomarev [Looks like](https://github.com/philip-gai/philip-gai/blob/main/README.md) it's back up! Thanks for the work 👍🏼

**Comment by antonkomarev** [comment]
Thank you for the reports guys. Problem fixed automatically, GitHub support isn't replied yet.
I've deleted all the direct links form your comments to not increment profile visits on this issue page loading.
