### ISSUE TITLE
Error fetching resource

### ISSUE THREAD

**Issue by impratik7** [antonkomarev/github-profile-views-counter#48]
Is the link down? 
Image not showing up? 
```
<img src="https://komarev.com/ghpvc/?username=impratik7&label=Profile%20views&color=0e75b6&style=flat" alt="impratik7" />
```

**Comment by seanpm2001** [comment]
I am having the same issue.

**Comment by antonkomarev** [comment]
Related to #47
We've moved our server to another IP address, it seems that it is not available from some locations. Researching this issue.

**Comment by oscar-defelice** [comment]
I have the same issue, however when I go to the link https://komarev.com/ghpvc/?username=oscar-defelice, the badge shows up good.

**Comment by antonkomarev** [comment]
Yep, it seems GitHub Camo Proxy service cached bad response. Created an issue in the GitHub Support.

**Comment by oscar-defelice** [comment]
I guess they solved the issue. 
<img src="https://camo.githubusercontent.com/8813dc99f11f44f616b28d561c892c1ab1522c14cee59d65f5119b1bee7265bb/68747470733a2f2f6b6f6d617265762e636f6d2f67687076632f3f757365726e616d653d6f736361722d646566656c696365">

**Comment by antonkomarev** [comment]
Thank you for the reports guys. Problem fixed automatically (looks like GitHub Camo cache issue), GitHub support isn't replied yet.
I've deleted all the direct links form your comments to not increment profile visits on this issue page loading.

**Comment by impratik7** [comment]
Thanks @antonkomarev , yup it's up now!!
