### ISSUE TITLE
Profile views tag increments everytime

### ISSUE THREAD

**Issue by rahuldkjain** [antonkomarev/github-profile-views-counter#5]
This can be seen even on opening or reloading my own profile , it needs improvement.

**Comment by antonkomarev** [comment]
Yes, this is how it should work. Every time you refresh page - counter will increment. It's not unique visitors count, it's views count.

**Comment by antonkomarev** [comment]
GitHub proxies images thru the `camo.githubusercontent.com` domain, so you we don't have any way to check if it's new user or somebody who already seen your profile today.

**Comment by rahuldkjain** [comment]
Gotcha! So we can't limit the visit count per IP .

**Comment by antonkomarev** [comment]
Nope. IPs are always the same.

**Comment by antonkomarev** [comment]
This is both good and bad. Bad - we cannot build more correct statistics. Good - these statistics completely anonymous.

**Comment by antonkomarev** [comment]
@rahuldkjain you've done nice generator tool! Good job!

**Comment by rahuldkjain** [comment]
Thanks @antonkomarev. To be honest I found this counter very useful and used it to develop a [github-profile-readme-generator](https://github.com/rahuldkjain/github-profile-readme-generator) tool.
