### ISSUE TITLE
[BUG] The counter resets?

### ISSUE THREAD

**Issue by TheBigEye** [antonkomarev/github-profile-views-counter#51]
1 - A week ago I had the counter around `2000`-`2250` views, then for some reason it appeared with only `2`, I think this started when I changed the style to `for-the-badge`

2 - I have also noticed that when you refresh the page with the counter it increases x2, that is, if you have 2 views, and you update you will then have 4, then 6, and so on...
![dung3](https://user-images.githubusercontent.com/63316583/164844225-eca7db7f-8f87-4e8d-8d6c-2b1a9333ff94.gif)

**Comment by antonkomarev** [comment]
Related to #50

**Comment by TheBigEye** [comment]
Thanks
