### ISSUE TITLE
Reset the counter

### ISSUE THREAD

**Issue by AmrElsayyad** [antonkomarev/github-profile-views-counter#56]
I want to know if there's a way to reset the counter.

**Comment by antonkomarev** [comment]
Nope, there is no way to reset the counter. I'd recommend you to migrate to yhype.me, it will have much more possibilities.

**Comment by antonkomarev** [comment]
Nope, there is no way to reset the counter. I'd recommend you to migrate to yhype.me, it will have much more possibilities.

#15

**Comment by AmrElsayyad** [comment]
Okay, thank you!
