### ISSUE TITLE
Can you please explain how you are counting the numbers of visitor

### ISSUE THREAD

**Issue by Kd-Here** [antonkomarev/github-profile-views-counter#58]
Hey @antonkomarev Thanks for amazing trick of markdown.

**I am new to github don't have idea how things happen but curious about them.** 
Could you please explain the actual processing how you keep track on count do you use sql and php or anyhthing else.

**Comment by antonkomarev** [comment]
@Kd-Here implementation is very simple, you can look in the `public` directory. There are file or DB storage available.
