### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by LevaniVashadze** [antonkomarev/github-profile-views-counter#60]
Badge doesn't show up for me and the website is not available aswell

**Comment by LevaniVashadze** [comment]
![](https://komarev.com/ghpvc/?username=LevaniVashadze&style=for-the-badge)

**Comment by antonkomarev** [comment]
Thank you for the report @LevaniVashadze will look on it this weekend

**Comment by antonkomarev** [comment]
Zabbix ate all server resources 💥

**Comment by antonkomarev** [comment]
@LevaniVashadze good news, all is ok with monitoring :) bad news, somebody DDoS my site

**Comment by LevaniVashadze** [comment]
Works now, thanks for the quick response
