### ISSUE TITLE
Server error while trying to sign up

### ISSUE THREAD

**Issue by Minipada** [antonkomarev/github-profile-views-counter#61]
Hi,

I'm trying to sign up but get a SERVER ERROR message displayed
![image](https://user-images.githubusercontent.com/1220912/232290202-9d8dd54e-480b-462d-8358-387e91a24e41.png)

I'm not sure what to do from there. I tried incognito mode, without browser extension but the same happens.

Thanks in advance

**Comment by antonkomarev** [comment]
@Minipada it happens sometimes because high service load. Try again later, should work
