### ISSUE TITLE
Attempting to use <div align="center"> seems to break it

### ISSUE THREAD

**Issue by cybrBeto** [antonkomarev/github-profile-views-counter#63]
works fine when copy and pasted as it is said in the guide, but when I add <div align="center"> in the line above and </div> in the line below, it seems to break the counter. is this a known issue?

**Comment by antonkomarev** [comment]
What do you mean by broken? What is not working?

**Comment by cybrBeto** [comment]
I have attached the screenshots showing what is happening. As you can see, when the code is not preceded by anything, it looks normal on the preview. When you try to align the button to the center, it seems to break the display, causing the button to now show on the preview and just the code. Is there any way to fix this? How would you go about aligning the button to the center

<img width="496" alt="Screenshot 2023-06-22 at 10 47 57 AM" src="https://github.com/antonkomarev/github-profile-views-counter/assets/137103052/f052f7d3-f818-4ec3-84a2-0172c3a94a32">
<img width="1040" alt="Screenshot 2023-06-22 at 10 48 29 AM" src="https://github.com/antonkomarev/github-profile-views-counter/assets/137103052/e33f8edf-9f91-4e46-900b-0bb509638b4f">
<img width="1040" alt="Screenshot 2023-06-22 at 10 48 50 AM" src="https://github.com/antonkomarev/github-profile-views-counter/assets/137103052/d13b01af-bb04-4de2-b7c2-456e2c04d763">
<img width="1040" alt="Screenshot 2023-06-22 at 10 49 04 AM" src="https://github.com/antonkomarev/github-profile-views-counter/assets/137103052/1650fb6b-4f34-4ed2-99ec-f8b42e503055">

**Comment by antonkomarev** [comment]
It's not related to this project. It's how GitHub markdown is working. You cannot mix html with markdown inside of it. Just use html `img` tag instead of markdown `![]()`
