### ISSUE TITLE
How to set the initial value

### ISSUE THREAD

**Issue by xumeng** [antonkomarev/github-profile-views-counter#64]
As I am migrating from another service, I would appreciate having an initial value set up.
Does it support this feature? 
Thanks~

**Comment by antonkomarev** [comment]
Do you have ideas how to do it securely without authorization?

**Comment by orhun** [comment]
Ah, I also need this feature since I don't want to take up more resources from the public instance.

> Do you have ideas how to do it securely without authorization?

Maybe with a config entry or an environment variable?

**Comment by Brikaa** [comment]
If I understand correctly, initial value means a value that the counter starts from instead of zero. Maybe one approach to do it would be to add this initial value on the fly without storing it on the server. It could be given as a query parameter.

The downside of this approach is that the user has the burden of remembering to include this initial value in the links.

What do you think @antonkomarev?

**Comment by antonkomarev** [comment]
@Brikaa if I understood you right — this is not secure. Anybody can place a link with your username in their page and drastically change your counter value.

I see 2 ways of solving this issue:
1. User creates some kind of gist in own namespace and makes http call to the ghpvc service. Service checks if the gist exists and gets new value for the set counter from it.
2. User login to https://yhype.me and goes to the settings. There are controls: reset counter, set initial value, migrate counter to the Y HYPE.

**Comment by Brikaa** [comment]
@antonkomarev I either don't understand the risk correctly or I wasn't clear enough. What I mean is that the counter would not be modified in the server storage.

The catch here is that, if you sum up the initial value and the counter value, the result will be the same as if you started from that initial value. We can do that without modifying the counter provided the initial value at each request. 

The counter in the server storage stays as it is, the initial value can be provided as a query parameter and the summation is returned. You remove the initial value, nothing is added. 

If someone uses the link with your username on his page and a different initial value, he would just get a counter with an added value. I don't think the victim is affected.

The downside is that you have to always have the initial value in the link.

**Comment by antonkomarev** [comment]
@Brikaa interesting idea. And it fixes possible issues with re-calculation counter aggregate value.

**Comment by antonkomarev** [comment]
I'm ready to review the solution @Brikaa described if someone interested in it.

**Comment by antonkomarev** [comment]
Thanks @Brikaa, feature is on prod!

You can provide a `base` number to add to the counter.
This is useful if you are migrating from another service.

For example, a user with 1000 views on another service who wants to migrate to GHPVC will use the following url
to ensure the 1000 views are accounted for:
```markdown
![](https://komarev.com/ghpvc/?username=your-github-username&base=1000)
```

**Comment by orhun** [comment]
That is absolutely great! I'm planning to host my own instance soon with this feature, thanks a lot!

**Comment by antonkomarev** [comment]
@orhun Not sure, I'm using it only for development. We are running it on bare metal. You can share stats with us later.
