### ISSUE TITLE
Bug it counts everytime I reloads the page

### ISSUE THREAD

**Issue by yogesh-hacker** [antonkomarev/github-profile-views-counter#65]
It counts my visitings also and the main problem as soon as I reloads the page it increases, but it have to remain same until a new GitHub user comes

**Comment by antonkomarev** [comment]
Read faq on the bottom of the readme file. It's not visitors counter, it's profile page views counter. It is impossible  to count visitors, GitHub does not allow to do that.

I recommend you to look on yhype.me as more feature rich alternative.
