### ISSUE TITLE
500 SERVER ERROR

### ISSUE THREAD

**Issue by Guaishou74851** [antonkomarev/github-profile-views-counter#73]
When attempting to access the page of https://yhype.me/, I frequently encounter a "500 Server Error." This issue seems to be occurring consistently in these two days.

![image](https://github.com/antonkomarev/github-profile-views-counter/assets/48148011/878f7d86-781b-4de0-bf67-a859558ad092)

**Comment by antonkomarev** [comment]
@Guaishou74851 fixed it

**Comment by MishaKav** [comment]
Tried now, have the same issue.

**Comment by antonkomarev** [comment]
@MishaKav it was fixed yesterday. There was an issues this morning, but we've found one more possible source of issues and fixed it.

**Comment by MishaKav** [comment]
It worked for some time, but now I still got the same error.

**Comment by Guaishou74851** [comment]
I also encounter the problem now. I recently access the page 10 times, but 8 of my 10 accesses are failed. 
![image](https://github.com/antonkomarev/github-profile-views-counter/assets/48148011/c8148352-123e-40fd-a4e0-66d7670f4036)

**Comment by antonkomarev** [comment]
We are working on it. Fixed for now. But it keeps crashing 1-2 times a day. We will notify when the issue will be completely resolved.

**Comment by antonkomarev** [comment]
We found 2 issues and resolved them. Closing this issue. Thanks for reporting!
