### ISSUE TITLE
[Feature suggestion] Timeline counter view

### ISSUE THREAD

**Issue by olmurphy** [antonkomarev/github-profile-views-counter#77]
It would be nice if their was a time line (like contributions timeline on Github repo) where a use could see a timeline of the number of visitors on a GitHub profile such as per month or per year.

This could be a better indication of profile traffic vs total view count all time.

If there is another free service let know otherwise :)

**Comment by antonkomarev** [comment]
@olmurphy 
Join https://yhype.me, it has much more features.
