### ISSUE TITLE
Condensed Counter View?

### ISSUE THREAD

**Issue by B-Salinas** [antonkomarev/github-profile-views-counter#78]
Noticed that the counter "shrunk" all of a sudden. I was at 2k views, nothing crazy big for the container to suddenly overflow. Attached screenshot below

<img width="132" alt="Screenshot 2023-10-10 at 2 40 48 PM" src="https://github.com/antonkomarev/github-profile-views-counter/assets/31112601/07e8e7b8-20ae-4a44-b5aa-471227b0ea24">

**Comment by AcoranGonzalezMoray** [comment]
I thought it was my problem, but I see that it is a problem with the server where it is hosted or it may be implementing some change currently. All we have to do is wait **(I hope the counter is not reset)**   :)

**Comment by amkkr** [comment]
I also noticed that and tried edit.  Server stopped returning images.
I hope it works as it did before.🙏

**Comment by antonkomarev** [comment]
Looks strange, need to investigate.

**Comment by kannanjayachandran** [comment]
Multiple issues have been opened for the same problem.

- Issue #79 
- Issue #80

**Comment by antonkomarev** [comment]
Temporary fix deployed. Going to make permanent one later, but should work now.

@B-Salinas @amkkr @AcoranGonzalezMoray @kannanjayachandran

**Comment by B-Salinas** [comment]
> Temporary fix deployed. Going to make permanent one later, but should work now.
> 
> 
> 
> @B-Salinas @amkkr @AcoranGonzalezMoray @kannanjayachandran @lim-yoona @igorskyflyer @Narennnnn

Thank you!! 🙏🏽🙌🏽
