### ISSUE TITLE
View Count Icon is shrinked

### ISSUE THREAD

**Issue by Narennnnn** [antonkomarev/github-profile-views-counter#80]
![Screenshot from 2023-10-11 10-59-27 (copy)](https://github.com/antonkomarev/github-profile-views-counter/assets/120191897/2cb0b823-eacb-43b2-9d25-ab2d10f47b5c)

There is some issue with view count icon as actual view count is not visible.

**Comment by antonkomarev** [comment]
Duplicate. Will notify about resolution here:
- #78
