### ISSUE TITLE
Expand the container when the views exceed the 3-digit number

### ISSUE THREAD

**Issue by syedasgarahmed** [antonkomarev/github-profile-views-counter#81]
Expand the container when the views exceed the 3-digit number (>100).

![image](https://github.com/antonkomarev/github-profile-views-counter/assets/73679838/58abbdb1-3c9a-4408-a3f9-13be3ce50e87)

**Comment by antonkomarev** [comment]
@syedasgarahmed @whoisdon Fixed it yesterday.
