### ISSUE TITLE
How can you self-host it? 

### ISSUE THREAD

**Issue by kRystalDevv** [antonkomarev/github-profile-views-counter#84]
I want to self-host it on my server, and the images made under my domain? 
is there a docker install? 
thanks

**Comment by orhun** [comment]
I think you can self-host it by using `docker-compose`: https://github.com/antonkomarev/github-profile-views-counter/blob/master/docker-compose.yaml

**Comment by antonkomarev** [comment]
As @orhun said there is docker compose that you can use to start.

It may be not production ready because we are using it for development only right now. But you are free to tune it for your preference.
