### ISSUE TITLE
How to get the views of repository? 

### ISSUE THREAD

**Issue by darshansharma** [antonkomarev/github-profile-views-counter#85]
Error: Expected a value to contain at most 39 characters
I wanted to show in the Readme file views of people who visited a particular repository.

To reproduce: let it count your traffic of some repository. 

Screenshot: 
<img width="582" alt="Screenshot 2023-12-23 at 8 37 06 AM" src="https://github.com/antonkomarev/github-profile-views-counter/assets/14093291/8dadf08a-b0c9-4ba2-95f0-30e98387692d">

**Comment by antonkomarev** [comment]
@darshansharma you need another solution. This counter designed to count profile hits only.

Try https://yhype.me because it fits  much better for this. You will be able to get much more information there. Not only repository views, but unique visitors count too.
