### ISSUE TITLE
how does it work?

### ISSUE THREAD

**Issue by adnjoo** [antonkomarev/github-profile-views-counter#90]
just curious..

is there a website watching the github page or? ..

**Comment by antonkomarev** [comment]
It's working like a tracking pixel. When somebody opens a page where you have this counter image — visitor's browser doing a request to the remote server, where the counter is increasing.

**Comment by adnjoo** [comment]
thank you

**Comment by razum2um** [comment]
@antonkomarev but doesn't camo proxy cache the badge? (for how long?)

**Comment by antonkomarev** [comment]
@razum2um no, because we are sending a header in the index.php:
```php
header('Cache-Control: max-age=0, no-cache, no-store, must-revalidate');
```
