### ISSUE TITLE
Make counter invisible till it reach some number

### ISSUE THREAD

**Issue by Aeliot-Tm** [antonkomarev/github-profile-views-counter#95]
Hi,

I'd like to make counter invisible till it reach some number. How could I do it?

**Comment by antonkomarev** [comment]
I recommend you to use https://yhype.me
It is private and more feature rich

**Comment by antonkomarev** [comment]
Another way to use pixel style, it will render an invisible pixel counter. You can look at how it works in the sources.

**Comment by Aeliot-Tm** [comment]
@antonkomarev  Thank you!

Done.
