### ISSUE TITLE
We need Github Repository Views

### ISSUE THREAD

**Issue by astola-studio** [antonkomarev/github-profile-views-counter#97]
Kindly consider creating a **Github Repository Views** too or **Page Views**, it’d be a much greater idea. We all appreciate this and will appreciate more.

**Comment by antonkomarev** [comment]
@astola-studio just use https://yhype.me, it has much more features

**Comment by piranhap** [comment]
Sorry for reopening this, but the url takes to godaddy to purchase the domain

**Comment by antonkomarev** [comment]
@piranhap thanks for reporting it. Edited. It's mobile keyboard word autofix broke the link 😅

re: @astola-studio
